name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: 'Build ğŸ—'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.HUB_GITHUB_TOKEN }}

    - name: Build the Docker image
      run:
        | # ä½¿ç”¨ ä¸Šä¸€æ­¥å†™çš„ Dockerfile æ„å»ºé•œåƒå¹¶å‘å¸ƒåˆ°ç§æœ‰ä»“åº“ï¼› å‘å¸ƒå®Œæˆå¯ä»¥å» https://github.com/MrGaoGang?tab=packages æŸ¥çœ‹
        docker build . --file Dockerfile --tag ghcr.io/wieszheng/bread-image:latest
        docker push ghcr.io/wieszheng/bread-image:latest
